refactor(esx_taxijob): Remove cb, use playerdata obj
esx-framework/esx_taxijob pull request #30
Opened 2023-11-19 16:58 UTC by Thekuca

2023-11-25 12:25 UTC, Thekuca commented
@Gellipapa awaiting review 😃

2023-11-25 12:46 UTC, Gellipapa requested changes

2023-11-25 12:46 UTC, Gellipapa commented on client/main.lua
> +                -- todo: refresh on callback
What is this todo? If you can refactor please implement this todo, or remove this comment.

2023-11-25 12:46 UTC, Gellipapa commented on client/main.lua
> -    end, function(menu)
This method handles the close callback, if you write outside it will always be set, I don't know how much of a problem this could be but I have a feeling it's running on a bug.

2023-12-16 13:33 UTC, Gellipapa commented
@Thekuca Hi! Any status?

2024-02-03 12:20 UTC, Gellipapa commented
@Thekuca Hi! Can you tested this?

2024-02-03 22:13 UTC, Thekuca commented
fixed tested done @Gellipapa

2024-02-29 21:00 UTC, Gellipapa commented
@Thekuca Hi! Why was this change made? The reason is that it is better to manage an inventory on the server side than on the client side, any problems that may occur during synchronization will not be handled with the correct data. 

Was there a performance issue with this?

2024-02-29 21:01 UTC, Gellipapa approved these changes
Code is approved.

2024-02-29 21:02 UTC, Gellipapa commented
Please don't merged, discuss why you made this change.

2024-03-25 19:12 UTC, closed without merging